import Header from "@/components/layout/header";
import "./globals.css";
import { Quicksand, Space_Mono } from "next/font/google";
import { GitHub, Linkedin, Youtube } from "react-feather";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
});

const spaceMono = Space_Mono({
  subsets: ["latin"],
  variable: "--font-spacemono",
  weight: "400",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${quicksand.variable} ${spaceMono.variable} bg-primary font-sans text-dark`}
    >
      <body className="flex min-h-screen flex-col">
        <Header />
        <main className="flex flex-1 flex-col items-center">{children}</main>
        <ul className="fixed bottom-4 left-4 flex flex-col gap-2">
          <li className="cursor-pointer">
            <a href="https://github.com/DLabbate">
              <GitHub strokeWidth={1} size={30} />
            </a>
          </li>
          <li>
            <a href="https://linkedin.com/in/domenic-labbate">
              <Linkedin strokeWidth={1} size={30} />
            </a>
          </li>
          <li>
            <a href="https://www.youtube.com/@domtheengineer">
              <Youtube strokeWidth={1} size={30} />
            </a>
          </li>
        </ul>
      </body>
    </html>
  );
}
