on:
  pull_request:
    branches:
      - master
jobs:
  jest-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Generate Contentlayer
        run: npm run build # Make sure this generates the .contentlayer folder
      - name: Run Jest tests
        run: npm test
        env:
          MONGODB_URI: mongodb://127.0.0.1:27017
  cypress-run:
    runs-on: ubuntu-latest
    needs: jest-run # Ensure Cypress runs only after Jest tests are complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          KV_REST_API_READ_ONLY_TOKEN: ${{ secrets.KV_REST_API_READ_ONLY_TOKEN }}
          KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
          KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
          KV_URL: ${{ secrets.KV_URL }}
