on:
  pull_request:
    branches:
      - master
jobs:
  env:
    DATABASE_URL: ${{ secrets.DATABASE_URL }}
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
